version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: buildtrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: buildtrack
    ports:
      - "5433:5432" # наружу 5433, внутри 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - buildtrack-net

  minio:
    image: minio/minio
    container_name: buildtrack-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - buildtrack-net

  backend:
    container_name: buildtrack-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/buildtrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
    command: >
      sh -c "./gradlew bootRun"
    networks:
      - buildtrack-net

volumes:
  pgdata:
  minio-data:

networks:
  buildtrack-net:
